apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-demo-autoscaler
  labels:
    app: istio-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-demo-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 40 # 40% of 3 requested cpu = 1.2 cores