apiVersion: v1
kind: Service
metadata:
  labels:
    name: demoservice
  name: demoservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8080
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: istio-demo
  type: LoadBalancer